# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import re
import sys
from PyQt5.uic import loadUi
from PyQt5.QtCore import Qt
from PyQt5 import uic, QtWidgets
from PyQt5.QtGui import QPixmap

from PyQt5.QtWidgets import QApplication, QMainWindow, QDialog, QLineEdit, QPushButton, QLabel, QGridLayout, QVBoxLayout, QHBoxLayout, QMessageBox, QWidget, QTableWidgetItem
import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsView, QGraphicsScene, QGraphicsPixmapItem
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    selected_row = -1

    def onItemClicked(self, it):
        self.selected_row = it.row()
        # print(self.tableWidget.item(it.row(), 0).text())
        self.marque.setText(self.tableWidget.item(it.row(), 0).text())
        self.modele.setText(self.tableWidget.item(it.row(), 1).text())
        self.type_de_carburant.setText(self.tableWidget.item(it.row(), 2).text())
        self.nombre_de_place.setText(self.tableWidget.item(it.row(), 3).text())
        self.transmission.setText(self.tableWidget.item(it.row(), 4).text())
        self.prix_de_location.setText(self.tableWidget.item(it.row(), 5).text())
        image_item = self.tableWidget.item(it.row(), 6)
        if image_item is not None:
            image_id = image_item.text()
            cnx = mysql.connector.connect(user="root", password="", host="localhost", database="location_voiture")

            # Retrieve the image data from the database
            mycursor = cnx.cursor()
            mycursor.execute("SELECT Image FROM voiture WHERE image_id = %s", (image_id,))
            result = mycursor.fetchone()
            Image = result[0]
        
            # Create a QPixmap object from the image data
            pixmap = QPixmap()
            pixmap.loadFromData(Image)

            # Create a QGraphicsPixmapItem object from the QPixmap
            pixmap_item = QGraphicsPixmapItem(pixmap)

            # Create a QGraphicsScene object and add the QGraphicsPixmapItem to it
            scene = QGraphicsScene()
            scene.addItem(pixmap_item)

            # Create a QGraphicsView object and set the QGraphicsScene as its scene
            view = QGraphicsView()
            view.setScene(scene)

            # Show the QGraphicsView widget
            view.show()
        else:
            # handle case where item has no image
            pass


        
    def onAddBtnClicked(self, it):
        print("clicked add", self.selected_row)
        rowPosition = self.tableWidget.rowCount()
        self.tableWidget.insertRow(rowPosition)
        cnx = mysql.connector.connect(user="root", password="", host="localhost", database="location_voiture")
        cursor = cnx.cursor()
        cursor.execute("INSERT INTO voiture (Marque, Modele, `Type de carburant`, `Nombre de places`, Transmission, `prix de location par jour`, Image, Disponibilite) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
        (self.marque.text(), self.modele.text(), self.type_de_carburant.text(), self.nombre_de_place.text(), self.transmission.text(), self.prix_de_location.text(), listOfCars[self.selected_row][3], listOfCars[self.selected_row][8]))
        cnx.commit()
        self.tableWidget.setItem(rowPosition , 0, QTableWidgetItem(self.marque.text()))
        self.tableWidget.setItem(rowPosition , 1, QTableWidgetItem(self.modele.text()))
        self.tableWidget.setItem(rowPosition , 2, QTableWidgetItem(self.type_de_carburant.text()))
        self.tableWidget.setItem(rowPosition , 3, QTableWidgetItem(self.nombre_de_place.text()))
        self.tableWidget.setItem(rowPosition , 4, QTableWidgetItem(self.transmission.text()))
        self.tableWidget.setItem(rowPosition , 5, QTableWidgetItem(self.prix_de_location.text()))
    def onEditBtnClicked(self, it):
        print("clicked edit", self.selected_row)
        print("db id:", listOfCars[self.selected_row][0])
        cnx = mysql.connector.connect(user="root", password="", host="localhost", database="location_voiture")
        cursor = cnx.cursor()
        cursor.execute("UPDATE voiture SET Marque=%s, Modele=%s, `Type de carburant`=%s, `Nombre de places`=%s, Transmission=%s, `prix de location par jour`=%s, Image=%s, Disponibilite=%s WHERE Voiture_id = %s",(self.marque.text(),
            self.modele.text(),
            self.type_de_carburant.text(),
            self.nombre_de_place.text(),
            self.transmission.text(),
            self.prix_de_location.text(),
            listOfCars[self.selected_row][3],
            listOfCars[self.selected_row][8],
            listOfCars[self.selected_row][0]))
        cnx.commit()
        self.tableWidget.setItem(self.selected_row, 0, QTableWidgetItem(self.marque.text()))
        self.tableWidget.setItem(self.selected_row, 1, QTableWidgetItem(self.modele.text()))
        self.tableWidget.setItem(self.selected_row, 2, QTableWidgetItem(self.type_de_carburant.text()))
        self.tableWidget.setItem(self.selected_row, 3, QTableWidgetItem(self.nombre_de_place.text()))
        self.tableWidget.setItem(self.selected_row, 4, QTableWidgetItem(self.transmission.text()))
        self.tableWidget.setItem(self.selected_row, 5, QTableWidgetItem(self.prix_de_location.text()))

    def onDeleteBtnClicked(self):
        selected_row = self.tableWidget.currentRow()
        if selected_row >= 0:
            confirm = QMessageBox.question(self.tableWidget, "Confirmer la suppression", "Êtes-vous sûr de vouloir supprimer cette voiture du tableau ?", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
            if confirm == QMessageBox.Yes:
                cnx = mysql.connector.connect(user="root", password="", host="localhost", database="location_voiture")
                cursor = cnx.cursor()
                cursor.execute("DELETE FROM voiture WHERE Voiture_id = %s", (listOfCars[selected_row][0],))
                cnx.commit()
                self.tableWidget.removeRow(selected_row)
       
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1202, 732)
        self.transmission_lbl = QtWidgets.QLabel(Form)
        self.transmission_lbl.setGeometry(QtCore.QRect(30, 501, 68, 16))
        self.transmission_lbl.setObjectName("transmission_lbl")
        self.return_3 = QtWidgets.QPushButton(Form)
        self.return_3.setGeometry(QtCore.QRect(530, 660, 131, 23))
        self.return_3.setObjectName("return_3")
        self.transmission = QtWidgets.QLineEdit(Form)
        self.transmission.setGeometry(QtCore.QRect(151, 499, 129, 20))
        self.transmission.setText("")
        self.transmission.setObjectName("transmission")
        self.modele = QtWidgets.QLineEdit(Form)
        self.modele.setGeometry(QtCore.QRect(151, 378, 129, 20))
        self.modele.setText("")
        self.modele.setObjectName("modele")
        self.marque = QtWidgets.QLineEdit(Form)
        self.marque.setGeometry(QtCore.QRect(151, 338, 129, 20))
        self.marque.setText("")
        self.marque.setObjectName("marque")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(300, 330, 881, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.delete_btn = QtWidgets.QPushButton(Form)
        self.delete_btn.setGeometry(QtCore.QRect(32, 593, 75, 23))
        self.delete_btn.setObjectName("delete_btn")
        self.marque_lbl_2 = QtWidgets.QLabel(Form)
        self.marque_lbl_2.setGeometry(QtCore.QRect(30, 370, 43, 16))
        self.marque_lbl_2.setObjectName("marque_lbl_2")
        self.add_btn = QtWidgets.QPushButton(Form)
        self.add_btn.setGeometry(QtCore.QRect(202, 593, 75, 23))
        self.add_btn.setObjectName("add_btn")
        self.prix_de_location = QtWidgets.QLineEdit(Form)
        self.prix_de_location.setGeometry(QtCore.QRect(151, 540, 129, 20))
        self.prix_de_location.setText("")
        self.prix_de_location.setObjectName("prix_de_location")
        self.marque_lbl = QtWidgets.QLabel(Form)
        self.marque_lbl.setGeometry(QtCore.QRect(30, 340, 43, 16))
        self.marque_lbl.setObjectName("marque_lbl")
        self.prixDeLocation_lbl = QtWidgets.QLabel(Form)
        self.prixDeLocation_lbl.setGeometry(QtCore.QRect(30, 542, 80, 16))
        self.prixDeLocation_lbl.setObjectName("prixDeLocation_lbl")
        self.nombre_de_place = QtWidgets.QLineEdit(Form)
        self.nombre_de_place.setGeometry(QtCore.QRect(151, 458, 129, 20))
        self.nombre_de_place.setText("")
        self.nombre_de_place.setObjectName("nombre_de_place")
        self.typeDeCarburant_lbl = QtWidgets.QLabel(Form)
        self.typeDeCarburant_lbl.setGeometry(QtCore.QRect(30, 419, 96, 16))
        self.typeDeCarburant_lbl.setObjectName("typeDeCarburant_lbl")
        self.ImageView = QtWidgets.QGraphicsView(Form)
        self.ImageView.setGeometry(QtCore.QRect(750, 60, 431, 261))
        self.ImageView = QtWidgets.QLabel(Form)
        self.ImageView.setGeometry(QtCore.QRect(320, 140, 256, 192))
        self.ImageView.setObjectName("ImageView")
        self.type_de_carburant = QtWidgets.QLineEdit(Form)
        self.type_de_carburant.setGeometry(QtCore.QRect(151, 417, 129, 20))
        self.type_de_carburant.setText("")
        self.type_de_carburant.setObjectName("type_de_carburant")
        self.edit_btn = QtWidgets.QPushButton(Form)
        self.edit_btn.setGeometry(QtCore.QRect(117, 593, 75, 23))
        self.edit_btn.setObjectName("edit_btn")
        self.nombreDePlace_lbl = QtWidgets.QLabel(Form)
        self.nombreDePlace_lbl.setGeometry(QtCore.QRect(30, 460, 92, 16))
        self.nombreDePlace_lbl.setObjectName("nombreDePlace_lbl")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.transmission_lbl.setText(_translate("Form", "Transmission :"))
        self.return_3.setText(_translate("Form", "Retourner vers le main"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Marque"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Modele"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Type de carburant"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Nombre de places"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Transmission"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Prix de location/j"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Image"))
        self.delete_btn.setText(_translate("Form", "Delete"))
        self.marque_lbl_2.setText(_translate("Form", "Modele :"))
        self.add_btn.setText(_translate("Form", "Add"))
        self.marque_lbl.setText(_translate("Form", "Marque :"))
        self.prixDeLocation_lbl.setText(_translate("Form", "Prix de location :"))
        self.typeDeCarburant_lbl.setText(_translate("Form", "Type de carburant :"))
        self.edit_btn.setText(_translate("Form", "Edit"))
        self.nombreDePlace_lbl.setText(_translate("Form", "Nombre de places :"))
        resLen = len(listOfCars)
        index = 0
        self.tableWidget.setRowCount(resLen)
        for item in listOfCars:
            print(index)
            self.tableWidget.setItem(index, 0, QTableWidgetItem(str(item[1])))
            self.tableWidget.setItem(index, 1, QTableWidgetItem(str(item[2])))
            self.tableWidget.setItem(index, 2, QTableWidgetItem(str(item[4])))
            self.tableWidget.setItem(index, 3, QTableWidgetItem(str(item[5])))
            self.tableWidget.setItem(index, 4, QTableWidgetItem(str(item[6])))
            self.tableWidget.setItem(index, 5, QTableWidgetItem(str(item[7])))
            index += 1
        
        self.tableWidget.itemClicked.connect(self.onItemClicked)
        self.add_btn.clicked.connect(self.onAddBtnClicked)
        self.edit_btn.clicked.connect(self.onEditBtnClicked)
        self.delete_btn.clicked.connect(self.onDeleteBtnClicked)
        self.return_3.clicked.connect(self.onDeleteBtnClicked)
        

cnx = mysql.connector.connect(user="root", password="", host="localhost", database="location_voiture")
cursor = cnx.cursor()
cursor.execute("SELECT * FROM voiture")
listOfCars = cursor.fetchall()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
