# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'liste.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import io
from PyQt5.QtGui import QImage, QPixmap
import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    

    def afficher_image_depuis_bdd(id_image):
        try:
            # Connexion à la base de données MySQL
            cnx = mysql.connector.connect(user='nom_utilisateur', password='mot_de_passe',
                                        host='adresse_hôte', database='nom_base_de_données')
            cursor = cnx.cursor()

            # Récupération de l'image en tant que blob à partir de la base de données
            query = "SELECT image_blob FROM table_images WHERE id = %s"
            cursor.execute(query, (id_image,))
            result = cursor.fetchone()
            if result is not None:
                image_blob = result[0]

                # Conversion du blob en QImage
                image = QImage()
                                        
                image.loadFromData(image_blob)

                # Conversion de l'image en QPixmap
                pixmap = QPixmap.fromImage(image)

                # Affichage de l'image dans un QLabel
                label = QLabel()
                label.setPixmap(pixmap)
                label.show()

            # Fermeture de la connexion à la base de données
            cursor.close()
            cnx.close()
        except mysql.connector.Error as err:
            print("Erreur MySQL : {}".format(err))
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 595)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
